services:
    eclipse-mosquitto:
        ports:
            - '1883:1883'
        volumes:
            - ./config:/mosquitto/config
            - ./log:/mosquitto/log
            - ./data:/mosquitto/data
        expose:
            - '1883'
        image: eclipse-mosquitto
        networks:
            sarea1:
                ipv4_address: 172.20.0.10

        
    publisher:
        build:
            context: .
        depends_on:
            - eclipse-mosquitto
        networks:
            - sarea1
            
networks:
    sarea1:
        name: sarea1
        ipam:
          config:
            - subnet: 172.20.0.0/16